# Configuration for accessing our buckets
data_ingestion:
  bucket_name: "mlops-project-animerecommender"
  bucket_file_names:
    - "anime.csv"
    - "anime_with_synopsis.csv"
    - "animelist.csv"

model:
  embedding_size: 128
  loss: binary_crossentropy  
  optimizer: Adam
  metrics: ["mae","mse"]

API:
  comet_ml_API: JaAUDgfxL3vDnPJB6wxFrSuaA